// components/TagPage.vue
<template>
  <div class="page">
    <h1>{{tag.name}}</h1>
    <div class="page__entries">
      <Entry v-for="article of articles"
             :key="article.slug"
             :article="article" />
    </div>
    <Pagination class="page__pagination"
                :page="page"
                :perPage="perPage"
                :total="total"
                :basePath="`/tags/${tag}`" />
  </div>
</template>

<script>
import Entry from '~/components/Entry';
import Pagination from '~/components/Pagination';

export default {
  components: {
    Entry,
    Pagination,
  },
  props: ['tag', 'articles', 'page', 'perPage', 'total'],
};
</script>

// src/components/tag/tag-page.tsx
import * as React from 'react';
import Page from '../page/page';
import PageSection from '../page/page-section';
import { Tag } from './types';
import { Article } from '../article';
import ArticleCard from '../article/article-card';
import Pagination from '../home/pagination';

interface TagPageProps {
  tag: Tag;
  articles: Article[];
  articlesPerPage: number;
  page: number;
  totalArticles: number;
}

class TagPage extends React.PureComponent<TagPageProps> {
  public render() {
    const {
      tag,
      articles,
      articlesPerPage,
      page,
      totalArticles,
    } = this.props;

    return (
      <Page>
        <PageSection>
          <h1>{tag.title}</h1>
        </PageSection>

        {articles.map((a, i) => (
          <ArticleCard article={a} key={i}/>
        ))}

        <Pagination basePath={`/tags/${tag.slug}`}
                    articlesPerPage={articlesPerPage}
                    page={page}
                    totalArticles={totalArticles}/>
      </Page>
    );
  }
}

export default TagPage;
