// src/components/home/home-page.tsx
import * as React from 'react';
import { Article, ArticleCard } from '../article';
import { Page } from '../page';
import Pagination from './pagination';

interface HomePageProps {
  page: number;
  articlesPerPage: number;
  totalArticles: number;
  articles: Article[];
}

class HomePage extends React.PureComponent<HomePageProps, {}> {
  public render() {
    const { page, articlesPerPage, totalArticles, articles } = this.props;

    return (
      <Page>
        {articles.map((article) => <ArticleCard article={article} key={article.slug}/>)}
        <Pagination page={page} articlesPerPage={articlesPerPage} totalArticles={totalArticles}/>
      </Page>
    );
  }
}

export default HomePage;

// components/HomePage.vue
<template>
  <div class="home">
    <div class="home__entries">
      <Entry v-for="article of articles"
             :key="article.slug"
             :article="article" />
    </div>
    <Pagination class="home__pagination"
                :page="page"
                :perPage="perPage"
                :total="total" />

  </div>
</template>

<script>
import Entry from '@/components/Entry';
import Pagination from '~/components/Pagination';

export default {
  components: {
    Entry,
    Pagination,
  },
  props: ['articles', 'page', 'perPage', 'total'],
};
</script>
