// src/components/pagination.jsx
import React from 'react';
import Link from 'gatsby-link';

const Pagination = props => {
  let prevLink =
    <Link to={props.page === 2 ? '/' : `/page/${props.page - 1}`}>
      prev
    </Link>;
  let nextLink =
    <Link to={`/page/${props.page + 1}`}>
      next
    </Link>;

  const pages = [];
  for (let i = 1; i <= props.total; i++) {
    pages.push(<Link key={i} to={i === 1 ? '/' : `/page/${i}`}>{i}</Link>);
  }

  return (
    <div>
      {prevLink}
      {pages}
      {nextLink}
    </div>
  );
};

export default Pagination;

// components/Pagination.vue
<template>
  <div>
    <nuxt-link v-if="page > 0"
               :to="page <= 1 ? `/` : `/page/${page - 1}`">
      Prev
    </nuxt-link>

    <nuxt-link v-for="i in total / perPage"
               :to="i == 1 ? '/' : '/page/' + (i - 1)"
               :key="i">
      {{i}}
    </nuxt-link>

    <nuxt-link v-if="page < (total / perPage - 1)"
               :to="`/page/${page + 1}`">
      Next
    </nuxt-link>
  </div>
</template>

<script>
export default {
  name: 'Pagination',
  props: ['page', 'perPage', 'total'],
};
</script>
